<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="notiondiagram"
    nsURI="http://notiondiagram/1.0" nsPrefix="notiondiagram">
  <eClassifiers xsi:type="ecore:EClass" name="NotionDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Relations" upperBound="-1"
        eType="#//Relation" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AttributeRelations" upperBound="-1"
        eType="#//AttributeRelation" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Generalizations" upperBound="-1"
        eType="#//Generalization" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Notions" upperBound="-1"
        eType="#//Notion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Package" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Notion">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Phrases" upperBound="-1"
        eType="#//Phrase" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Phrase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" transient="true" defaultValueLiteral="" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generalization" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeRelation" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SourceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TargetId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRelation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" lowerBound="1"
        eType="#//Notion"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Target" lowerBound="1"
        eType="#//Notion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectedRelation" eSuperTypes="#//Relation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="#//AbstractRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TargetMultiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SourceMultiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Stereotype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" transient="true" defaultValueLiteral="" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndirectRelation" eSuperTypes="#//Relation"/>
</ecore:EPackage>
